[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/public"
  to = "/public.html"
  status = 200

[functions."daily-briefing"]
  schedule = "0 23 * * *"

[[redirects]]
  from = "/api/briefing"
  to = "/.netlify/functions/briefing"
  status = 200
